dist: trusty
language: node_js
node_js:
- '6.1'
sudo: true
before_install:
- npm i electron-packager -g
- sudo dpkg --add-architecture i386
- sudo apt-get -qq update
- sudo apt-get install wine1.6 lftp
install: npm install
script: electron-packager ./ Elektronswer --all
env:
  global:
  - secure: t/Wes4TgwqYEfbiZHzs0nx8myXQESBPId415Od9jbFgaH58+MV46BY95zoVRr71ME18utdgXkz6lAtJQTW/W4v2HPDdtjd/ptJJTTJ1szOS2iYvYSUyRGYCz0GTCkGhIyQrFpSl4gNebVJvF7tDirgwZ2mHM74hGNi/IwLE8s+gy3nzLbQWLoWBZFytlb+WLbd/v70A4zyKjy+/n5U424ecBlFiCxhXym7ECIRDW42manwshceaRPsV22kN2IfPsGabA1wm0EOylj1TlN0ZBPUj/KkOc0i0fHlz7tD9pJSkckXJCTpyCyeq7SaMqno16ztDU8XmSvFlV8xKYe8uW/s6E1GqtfvBxHcj9clYH8/xmI02i7HQDgc7SDuB6N6WUxKVd931Xn/08cGUk59DgrfGcyCg/BFQbOTt6ugfZwir8B/bcw9eQT+/jzR5PUiDuu+Me1OMIeE7TxOKdfaPctxULE+2OrpzomTiwzfvM4LaBwWXUsUv6NUZRnP1YbcK54JBL6ypxbYigbAa7Ol3gZ+C+0nbEy2OxmRdfQjjPh98xSRgWw5e12yvOLbz1unoIJ3KauXUo/xNe49q42K/XQExAEpgrU48DX14VpoMRwq/KYTO25JKYFaFvw8lF/dxYnPVQ7GsFV8akJYhQC2odMf8EjlDPLJdoBZUZa5YHm30=
  - secure: x5pigvVSaNoeace8pxNtL6Go7E3uQ0e1nGlFgG5WNF0lPG5dOKfhPNAJ+zn5fsbh3JNaDaaczhOaUNuJb21CiutsSFDA1OfHs89pXcj/cWZ53rI9JaE9vrWY8i2cOZFugMtiXJo9waATrOMjN3x3Tlamjd6I4YNdhTZy/uVnGqsKVemLkXybiB+xsGCLOGogsxC+NA321AH1WLG5nEKnpxvfXhzt0NUIq8zQTt7whTcpXMcjquwAUSXM//h7l+e+oAMaSCnCNn7peNotd4DTN/APmxrgcSVrOzgR+zGwBLPjNNDaAcydm5yvO/LrrgjVla0ZC1T4pCKJ+wymWr2kYMtlpctKNat6EOW4+joWXJmaL8ABM6f+MSOLuYUF/7PwsvnK812jFxAPvVERRK7f/sRTgJMnxrAxBhAOXlG/DnglEs6W+YgoXLXiPZvIyarsSeexZQbOlZaMyNJxH2axu7k7IEdvGRiv1Hz3rhyjjeks1HBh5c30M6lfhiziMRZB/Xq8sWMBeGtOBosLqGnH8x5pRNGch7QQTVXevV63ABR8wm0COBNLUHgD52MQO8hossYrNbvte9pYkrnDq+RAYFzyHMwczp0J6fWG2gXBiYNcnELUNjSsC0zBDJLouj/00sGPV4+hIiHIaWmyZD/T0II+kf2VibqIExji74h/Ysg=
  - secure: 5jHa98OQHPWwZBN+BBrdEEidBaV0BEv5Nast35Mw+4rxkZhLIQSZ2KIeJFh1A2FhUykLpI6YOY/NnH+ABC7PcSyc8kbroV/RNR8+DntRWJ+wZe5KAq2qWEVjrjuIjFq4meka5Bd96XU2YG5kCh1JIx4lw9DswPtxNqvgxqUmSBycrE5og17pBNEB+xfNnI8JI20ANXz2NJ3s1TBC4b7fl1dyj+Bykk81U9xKSKEyQM3VCTE9TsIehMlh/dsUShnGKfmySM37F2Bc2bqBAOdjpxoPr7ZFNfDK3XkPHdIjoxn8MJvx0C+ItfPMTrWuJR4GkwKAgdUI4KmdWE/KOMd63gLXA0e+Wn8vlV1P3fmteJwQaoXudVKI7chcXBq2/d4xu+9xePD1yhiO3uqCVbKM4mRqLjzZAnlTOnpMfCKX8/iRhzXpUBy8ioL01EFMfGgifID2wfw9ndONpvMqg6aba3HGoSsRdn/6TbcGZ/dz05yFtsOSRECZtA0eRAPm7aUq6McSt536rurnSIbr+mje5eLoZY3dAV+J634P/sHJJIz/8fO5RoLWNNqH5qqsKYVIO82R446FTIYF7IfW9rlXTZs0LSQ/5BWsGyO7vZiww9OYHCFPPfGnL9Wzzf7JPhQ1F74YwKQYoyip4C0bSIYJRhxfZJbLuR8AxJdjdXx8KK8=
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: gob197yog0U7Pzr/rAS9XqCSJubNpTcSqHJpVlM9YKfVRBdSR770/cn2lYl1YdNlIkoXZUlLsmetG/dTpnytKXK8GyI5FLgO1BdaWgFKfYoWcEbQoESnnDF/GKW4zDfE4Kxl9yJZmR3xrgJ3FLhWUDq1K93P1oi/716jsYMXfOkPtNu6vngLgM0CzhKtjpGvlC6iTCqf3Qx6xs6i2w5Gs3mdQeghzIpxOd2a4Q8HqucO769zORPQGt6DZi2lbhNr5SwKcvTyxCcJEJIvfS6dveYfAl6lkVukjHXBu3kefbSlpyIvC6MOM58E1K+2Z+tRU83s9np486rMvGXGpwBklDg1Gcrq7gZuBN8Nkj4ZrypqaPVLKxwp1MF/6MGoGMNXcBkSZcg366KN7AMpWAmNvXkaDG9ZImhLfAsM3r34ukhvduOSRTZqUMIg+yet8S2SBKPTyoiWeRFKaHZ0AjITJJmUGLgwp9XzyrC6C8JaDZ2TyiuYL9eYoTVx0tqIQOOsBpirC2FP/PsQpiKSgnjlD/+EcTzCaIJhKyzahjKxgPDOESEYt+IQzU/G4ExNA2wHWNGimGLKYzr8kRWwNs/wNIgF9x6NpXS3EyCpLuWO4pDqrESYWO0+5fY+aCYPZKr2/rAOMzKA33OZOQyQ44kGBr5maQfwf+AfQTPYmLX9gbc=
  file:
  - elektronswer-mac64.zip
  - elektronswer-win32.zip
  - elektronswer-win64.zip
  - elektronswer-linux64.tar.gz
  - elektronswer-linux32.tar.gz
  on:
    repo: solvillan/elektronswer
