language: node_js
node_js:
  - "0.12"
sudo: require
before_install: sudo npm i electron-packager -g
script: npm install && electron-packager ./ Elektronswer --platform=all --arch=all --version=0.29.2
